// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/ids.dart';
import 'package:zonai_schema/zonai_schema.dart';

final class Assignment {
  Assignment({
    required this.id,
    required this.ownerId,
    required this.courseId,
    required this.title,
    required this.description,
    required this.rubricDocument,
    this.sourceRubricId,
    this.dueOn,
    required this.pointsPossible,
    required this.closed,
    required this.createdOn,
    required this.rev,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  final AssignmentsId id;
  final String ownerId;
  final String courseId;
  final String title;
  final String description;
  final String rubricDocument;
  final String? sourceRubricId;
  final int? dueOn;
  final double pointsPossible;
  final bool closed;
  final int createdOn;
  final int rev;
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? deletedAt;
}

/// Synced with zonai_sync: owner-scoped, revisioned, tombstoned, and a
/// NON-null updated_at so zonai stamps it on insert (sync cursors need it).
final class AssignmentTable extends Table<Assignment> {
  AssignmentTable(super.$)
    : id = $.id(
        'id',
        (s) => s.id,
        fromString: AssignmentsId.new,
        generate: AssignmentsId.generate,
      ),
      ownerId = $.text('owner_id', (s) => s.ownerId),
      courseId = $.text('course_id', (s) => s.courseId),
      title = $.text('title', (s) => s.title),
      description = $.text('description', (s) => s.description),
      rubricDocument = $.text('rubric_document', (s) => s.rubricDocument),
      sourceRubricId = $.text('source_rubric_id', (s) => s.sourceRubricId),
      dueOn = $.integer('due_on', (s) => s.dueOn),
      pointsPossible = $.real('points_possible', (s) => s.pointsPossible),
      closed = $.boolean('closed', (s) => s.closed),
      createdOn = $.integer('created_on', (s) => s.createdOn),
      rev = $.integer('rev', (s) => s.rev),
      createdAt = $.createdAt('created_at', (s) => s.createdAt),
      updatedAt = $.updatedAt('updated_at', (s) => s.updatedAt),
      deletedAt = $.dateTime('deleted_at', (s) => s.deletedAt);

  @override
  Assignment fromRow(RowReader read) => Assignment(
    id: read(id),
    ownerId: read(ownerId),
    courseId: read(courseId),
    title: read(title),
    description: read(description),
    rubricDocument: read(rubricDocument),
    sourceRubricId: read(sourceRubricId),
    dueOn: read(dueOn),
    pointsPossible: read(pointsPossible),
    closed: read(closed),
    createdOn: read(createdOn),
    rev: read(rev),
    createdAt: read(createdAt),
    updatedAt: read(updatedAt),
    deletedAt: read(deletedAt),
  );

  final IdColumn<AssignmentsId> id;
  final ColumnType<String> ownerId;
  final ColumnType<String> courseId;
  final ColumnType<String> title;
  final ColumnType<String> description;
  final ColumnType<String> rubricDocument;
  final ColumnType<String?> sourceRubricId;
  final ColumnType<int?> dueOn;
  final ColumnType<double> pointsPossible;
  final ColumnType<bool> closed;
  final ColumnType<int> createdOn;
  final ColumnType<int> rev;
  final DateTimeColumn createdAt;
  final DateTimeColumn updatedAt;
  final ColumnType<DateTime?> deletedAt;
}

final assignments = table('assignments', AssignmentTable.new);
