// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/ids.dart';
import 'package:zonai_schema/zonai_schema.dart';

final class CommentSnippet {
  CommentSnippet({
    required this.id,
    required this.ownerId,
    required this.body,
    required this.category,
    required this.useCount,
    required this.rev,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  final CommentSnippetsId id;
  final String ownerId;
  final String body;
  final String category;
  final int useCount;
  final int rev;
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? deletedAt;
}

/// Synced with zonai_sync: owner-scoped, revisioned, tombstoned, and a
/// NON-null updated_at so zonai stamps it on insert (sync cursors need it).
final class CommentSnippetTable extends Table<CommentSnippet> {
  CommentSnippetTable(super.$)
    : id = $.id(
        'id',
        (s) => s.id,
        fromString: CommentSnippetsId.new,
        generate: CommentSnippetsId.generate,
      ),
      ownerId = $.text('owner_id', (s) => s.ownerId),
      body = $.text('body', (s) => s.body),
      category = $.text('category', (s) => s.category),
      useCount = $.integer('use_count', (s) => s.useCount),
      rev = $.integer('rev', (s) => s.rev),
      createdAt = $.createdAt('created_at', (s) => s.createdAt),
      updatedAt = $.updatedAt('updated_at', (s) => s.updatedAt),
      deletedAt = $.dateTime('deleted_at', (s) => s.deletedAt);

  @override
  CommentSnippet fromRow(RowReader read) => CommentSnippet(
    id: read(id),
    ownerId: read(ownerId),
    body: read(body),
    category: read(category),
    useCount: read(useCount),
    rev: read(rev),
    createdAt: read(createdAt),
    updatedAt: read(updatedAt),
    deletedAt: read(deletedAt),
  );

  final IdColumn<CommentSnippetsId> id;
  final ColumnType<String> ownerId;
  final ColumnType<String> body;
  final ColumnType<String> category;
  final ColumnType<int> useCount;
  final ColumnType<int> rev;
  final DateTimeColumn createdAt;
  final DateTimeColumn updatedAt;
  final ColumnType<DateTime?> deletedAt;
}

final commentSnippets = table('comment_snippets', CommentSnippetTable.new);
