// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/ids.dart';
import 'package:zonai_schema/zonai_schema.dart';

final class Course {
  Course({
    required this.id,
    required this.ownerId,
    required this.name,
    required this.section,
    required this.term,
    required this.archived,
    required this.createdOn,
    required this.rev,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  final CoursesId id;
  final String ownerId;
  final String name;
  final String section;
  final String term;
  final bool archived;
  final int createdOn;
  final int rev;
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? deletedAt;
}

/// Synced with zonai_sync: owner-scoped, revisioned, tombstoned, and a
/// NON-null updated_at so zonai stamps it on insert (sync cursors need it).
final class CourseTable extends Table<Course> {
  CourseTable(super.$)
    : id = $.id(
        'id',
        (s) => s.id,
        fromString: CoursesId.new,
        generate: CoursesId.generate,
      ),
      ownerId = $.text('owner_id', (s) => s.ownerId),
      name = $.text('name', (s) => s.name),
      section = $.text('section', (s) => s.section),
      term = $.text('term', (s) => s.term),
      archived = $.boolean('archived', (s) => s.archived),
      createdOn = $.integer('created_on', (s) => s.createdOn),
      rev = $.integer('rev', (s) => s.rev),
      createdAt = $.createdAt('created_at', (s) => s.createdAt),
      updatedAt = $.updatedAt('updated_at', (s) => s.updatedAt),
      deletedAt = $.dateTime('deleted_at', (s) => s.deletedAt);

  @override
  Course fromRow(RowReader read) => Course(
    id: read(id),
    ownerId: read(ownerId),
    name: read(name),
    section: read(section),
    term: read(term),
    archived: read(archived),
    createdOn: read(createdOn),
    rev: read(rev),
    createdAt: read(createdAt),
    updatedAt: read(updatedAt),
    deletedAt: read(deletedAt),
  );

  final IdColumn<CoursesId> id;
  final ColumnType<String> ownerId;
  final ColumnType<String> name;
  final ColumnType<String> section;
  final ColumnType<String> term;
  final ColumnType<bool> archived;
  final ColumnType<int> createdOn;
  final ColumnType<int> rev;
  final DateTimeColumn createdAt;
  final DateTimeColumn updatedAt;
  final ColumnType<DateTime?> deletedAt;
}

final courses = table('courses', CourseTable.new);
