// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/ids.dart';
import 'package:zonai_schema/zonai_schema.dart';

final class Evaluation {
  Evaluation({
    required this.id,
    required this.ownerId,
    required this.assignmentId,
    required this.studentId,
    required this.status,
    required this.document,
    required this.updatedOn,
    required this.rev,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  final EvaluationsId id;
  final String ownerId;
  final String assignmentId;
  final String studentId;
  final String status;
  final String document;
  final int updatedOn;
  final int rev;
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? deletedAt;
}

/// Synced with zonai_sync: owner-scoped, revisioned, tombstoned, and a
/// NON-null updated_at so zonai stamps it on insert (sync cursors need it).
final class EvaluationTable extends Table<Evaluation> {
  EvaluationTable(super.$)
    : id = $.id(
        'id',
        (s) => s.id,
        fromString: EvaluationsId.new,
        generate: EvaluationsId.generate,
      ),
      ownerId = $.text('owner_id', (s) => s.ownerId),
      assignmentId = $.text('assignment_id', (s) => s.assignmentId),
      studentId = $.text('student_id', (s) => s.studentId),
      status = $.text('status', (s) => s.status),
      document = $.text('document', (s) => s.document),
      updatedOn = $.integer('updated_on', (s) => s.updatedOn),
      rev = $.integer('rev', (s) => s.rev),
      createdAt = $.createdAt('created_at', (s) => s.createdAt),
      updatedAt = $.updatedAt('updated_at', (s) => s.updatedAt),
      deletedAt = $.dateTime('deleted_at', (s) => s.deletedAt);

  @override
  Evaluation fromRow(RowReader read) => Evaluation(
    id: read(id),
    ownerId: read(ownerId),
    assignmentId: read(assignmentId),
    studentId: read(studentId),
    status: read(status),
    document: read(document),
    updatedOn: read(updatedOn),
    rev: read(rev),
    createdAt: read(createdAt),
    updatedAt: read(updatedAt),
    deletedAt: read(deletedAt),
  );

  final IdColumn<EvaluationsId> id;
  final ColumnType<String> ownerId;
  final ColumnType<String> assignmentId;
  final ColumnType<String> studentId;
  final ColumnType<String> status;
  final ColumnType<String> document;
  final ColumnType<int> updatedOn;
  final ColumnType<int> rev;
  final DateTimeColumn createdAt;
  final DateTimeColumn updatedAt;
  final ColumnType<DateTime?> deletedAt;
}

final evaluations = table('evaluations', EvaluationTable.new);
