// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/ids.dart';
import 'package:zonai_schema/zonai_schema.dart';

final class Rubric {
  Rubric({
    required this.id,
    required this.ownerId,
    required this.title,
    required this.subject,
    required this.isTemplate,
    required this.archived,
    required this.document,
    required this.createdOn,
    required this.rev,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  final RubricsId id;
  final String ownerId;
  final String title;
  final String subject;
  final bool isTemplate;
  final bool archived;
  final String document;
  final int createdOn;
  final int rev;
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? deletedAt;
}

/// Synced with zonai_sync: owner-scoped, revisioned, tombstoned, and a
/// NON-null updated_at so zonai stamps it on insert (sync cursors need it).
final class RubricTable extends Table<Rubric> {
  RubricTable(super.$)
    : id = $.id(
        'id',
        (s) => s.id,
        fromString: RubricsId.new,
        generate: RubricsId.generate,
      ),
      ownerId = $.text('owner_id', (s) => s.ownerId),
      title = $.text('title', (s) => s.title),
      subject = $.text('subject', (s) => s.subject),
      isTemplate = $.boolean('is_template', (s) => s.isTemplate),
      archived = $.boolean('archived', (s) => s.archived),
      document = $.text('document', (s) => s.document),
      createdOn = $.integer('created_on', (s) => s.createdOn),
      rev = $.integer('rev', (s) => s.rev),
      createdAt = $.createdAt('created_at', (s) => s.createdAt),
      updatedAt = $.updatedAt('updated_at', (s) => s.updatedAt),
      deletedAt = $.dateTime('deleted_at', (s) => s.deletedAt);

  @override
  Rubric fromRow(RowReader read) => Rubric(
    id: read(id),
    ownerId: read(ownerId),
    title: read(title),
    subject: read(subject),
    isTemplate: read(isTemplate),
    archived: read(archived),
    document: read(document),
    createdOn: read(createdOn),
    rev: read(rev),
    createdAt: read(createdAt),
    updatedAt: read(updatedAt),
    deletedAt: read(deletedAt),
  );

  final IdColumn<RubricsId> id;
  final ColumnType<String> ownerId;
  final ColumnType<String> title;
  final ColumnType<String> subject;
  final ColumnType<bool> isTemplate;
  final ColumnType<bool> archived;
  final ColumnType<String> document;
  final ColumnType<int> createdOn;
  final ColumnType<int> rev;
  final DateTimeColumn createdAt;
  final DateTimeColumn updatedAt;
  final ColumnType<DateTime?> deletedAt;
}

final rubrics = table('rubrics', RubricTable.new);
