// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/ids.dart';
import 'package:zonai_schema/zonai_schema.dart';

final class Student {
  Student({
    required this.id,
    required this.ownerId,
    required this.courseId,
    required this.firstName,
    required this.lastName,
    required this.studentNumber,
    required this.email,
    required this.notes,
    required this.archived,
    required this.rev,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  final StudentsId id;
  final String ownerId;
  final String courseId;
  final String firstName;
  final String lastName;
  final String studentNumber;
  final String email;
  final String notes;
  final bool archived;
  final int rev;
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? deletedAt;
}

/// Synced with zonai_sync: owner-scoped, revisioned, tombstoned, and a
/// NON-null updated_at so zonai stamps it on insert (sync cursors need it).
final class StudentTable extends Table<Student> {
  StudentTable(super.$)
    : id = $.id(
        'id',
        (s) => s.id,
        fromString: StudentsId.new,
        generate: StudentsId.generate,
      ),
      ownerId = $.text('owner_id', (s) => s.ownerId),
      courseId = $.text('course_id', (s) => s.courseId),
      firstName = $.text('first_name', (s) => s.firstName),
      lastName = $.text('last_name', (s) => s.lastName),
      studentNumber = $.text('student_number', (s) => s.studentNumber),
      email = $.text('email', (s) => s.email),
      notes = $.text('notes', (s) => s.notes),
      archived = $.boolean('archived', (s) => s.archived),
      rev = $.integer('rev', (s) => s.rev),
      createdAt = $.createdAt('created_at', (s) => s.createdAt),
      updatedAt = $.updatedAt('updated_at', (s) => s.updatedAt),
      deletedAt = $.dateTime('deleted_at', (s) => s.deletedAt);

  @override
  Student fromRow(RowReader read) => Student(
    id: read(id),
    ownerId: read(ownerId),
    courseId: read(courseId),
    firstName: read(firstName),
    lastName: read(lastName),
    studentNumber: read(studentNumber),
    email: read(email),
    notes: read(notes),
    archived: read(archived),
    rev: read(rev),
    createdAt: read(createdAt),
    updatedAt: read(updatedAt),
    deletedAt: read(deletedAt),
  );

  final IdColumn<StudentsId> id;
  final ColumnType<String> ownerId;
  final ColumnType<String> courseId;
  final ColumnType<String> firstName;
  final ColumnType<String> lastName;
  final ColumnType<String> studentNumber;
  final ColumnType<String> email;
  final ColumnType<String> notes;
  final ColumnType<bool> archived;
  final ColumnType<int> rev;
  final DateTimeColumn createdAt;
  final DateTimeColumn updatedAt;
  final ColumnType<DateTime?> deletedAt;
}

final students = table('students', StudentTable.new);
