name: rubric
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_svg: ^0.19.1
  double_linked_list: ^1.0.8 # Used for weight calculations on assign_weights
  font_awesome_flutter: ^8.11.0
  flutter_riverpod: ^0.13.0 # State management / Dependency Injection (for testing)
  flow_builder: ^0.0.1-dev.11 # Navigation
  dotted_border: ^1.0.7
  onboarding:
    git: https://github.com/SupposedlySam/onboarding.git

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.2.1

import_sorter:
  comments: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Avenir-Black
      fonts:
        - asset: assets/custom_fonts/Avenir-Black.ttf
          weight: 900
    - family: Avenir-Heavy
      fonts:
        - asset: assets/custom_fonts/Avenir-Heavy.ttf
          weight: 800  
    - family: Avenir-Light
      fonts:
        - asset: assets/custom_fonts/Avenir-Light.ttf
          weight: 100      

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.svg
    - assets/images/icon-lock-default.svg
    - assets/images/icon-lock-locked.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # TODO: Add https://github.com/VeryGoodOpenSource/very_good_analysis/blob/main/lib/analysis_options.2.3.0.yaml
  # TODO: https://dart.dev/null-safety/migration-guide: to do w/ JW
  # TODO: Fix technical debt issues: updating all strings to include arb file throughout app