// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:zonai_schema/zonai_schema.dart' as z;

/// Any string is accepted: ids are chosen by clients (created offline).
final class UsersId implements z.Id {
  const UsersId(this.value);

  factory UsersId.generate() =>
      UsersId('${DateTime.now().microsecondsSinceEpoch}_user');

  @override
  final String value;

  @override
  String toString() => value;

  String toJson() => value;
}

/// Any string is accepted: ids are chosen by clients (created offline).
final class RubricsId implements z.Id {
  const RubricsId(this.value);

  factory RubricsId.generate() =>
      RubricsId('${DateTime.now().microsecondsSinceEpoch}_rubr');

  @override
  final String value;

  @override
  String toString() => value;

  String toJson() => value;
}

/// Any string is accepted: ids are chosen by clients (created offline).
final class CoursesId implements z.Id {
  const CoursesId(this.value);

  factory CoursesId.generate() =>
      CoursesId('${DateTime.now().microsecondsSinceEpoch}_cour');

  @override
  final String value;

  @override
  String toString() => value;

  String toJson() => value;
}

/// Any string is accepted: ids are chosen by clients (created offline).
final class StudentsId implements z.Id {
  const StudentsId(this.value);

  factory StudentsId.generate() =>
      StudentsId('${DateTime.now().microsecondsSinceEpoch}_stud');

  @override
  final String value;

  @override
  String toString() => value;

  String toJson() => value;
}

/// Any string is accepted: ids are chosen by clients (created offline).
final class AssignmentsId implements z.Id {
  const AssignmentsId(this.value);

  factory AssignmentsId.generate() =>
      AssignmentsId('${DateTime.now().microsecondsSinceEpoch}_assi');

  @override
  final String value;

  @override
  String toString() => value;

  String toJson() => value;
}

/// Any string is accepted: ids are chosen by clients (created offline).
final class EvaluationsId implements z.Id {
  const EvaluationsId(this.value);

  factory EvaluationsId.generate() =>
      EvaluationsId('${DateTime.now().microsecondsSinceEpoch}_eval');

  @override
  final String value;

  @override
  String toString() => value;

  String toJson() => value;
}

/// Any string is accepted: ids are chosen by clients (created offline).
final class CommentSnippetsId implements z.Id {
  const CommentSnippetsId(this.value);

  factory CommentSnippetsId.generate() =>
      CommentSnippetsId('${DateTime.now().microsecondsSinceEpoch}_comm');

  @override
  final String value;

  @override
  String toString() => value;

  String toJson() => value;
}
