// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/schemas/assignments.dart';
import 'package:zonai_schema/zonai_schema.dart';

AssignmentTableRules main() => AssignmentTableRules();

/// Signed-in users may ask; the row rules decide. canUpdate must be allowed
/// here: zonai checks table rules BEFORE looking the row up.
final class AssignmentTableRules
    extends TableRules<AssignmentTable, Assignment> {
  AssignmentTableRules() : super(assignments);

  @override
  Future<bool> canView(Jwt? jwt) async => jwt != null;

  @override
  Future<bool> canList(Jwt? jwt) async => jwt != null;

  @override
  Future<bool> canCreate(Jwt? jwt) async => jwt != null;

  @override
  Future<bool> canUpdate(Jwt? jwt) async => jwt != null;

  @override
  Future<bool> canDelete(Jwt? jwt) async => false;
}
