// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/schemas/assignments.dart';
import 'package:zonai_schema/zonai_schema.dart';

AssignmentRowRules main() => AssignmentRowRules();

/// A teacher sees and changes only their own rows. Ownership is checked on
/// both sides of an update so a row can't be handed to someone else. Hard
/// deletes are only for account deletion, and only of the caller's own rows;
/// everyday sync deletes are tombstones.
final class AssignmentRowRules extends RowRules<AssignmentTable, Assignment> {
  AssignmentRowRules() : super(assignments);

  bool _owns(Jwt? jwt, Assignment row) =>
      jwt != null && jwt.userId.value == row.ownerId;

  /// Reads are narrowed to the caller's rows (zonai #45): an unscoped list
  /// returns "your rows" instead of a 403, and counts take the plain-COUNT
  /// path while still counting only what the caller may see. canView still
  /// runs on every row in scope.
  @override
  Future<Where?> viewScope(Jwt? jwt) async =>
      jwt == null ? null : Eq('owner_id', jwt.userId.value);

  @override
  Future<bool> canView(Jwt? jwt, Assignment row) async => _owns(jwt, row);

  @override
  Future<bool> canCreate(Jwt? jwt, Assignment row) async => _owns(jwt, row);

  @override
  Future<bool> canUpdate(Jwt? jwt, Assignment before, Assignment after) async =>
      _owns(jwt, before) && _owns(jwt, after);

  @override
  Future<bool> canDelete(Jwt? jwt, Assignment row) async => _owns(jwt, row);
}
