// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/schemas/comment_snippets.dart';
import 'package:zonai_schema/zonai_schema.dart';

CommentSnippetTableRules main() => CommentSnippetTableRules();

/// Signed-in users may ask; the row rules decide. canUpdate must be allowed
/// here: zonai checks table rules BEFORE looking the row up.
final class CommentSnippetTableRules
    extends TableRules<CommentSnippetTable, CommentSnippet> {
  CommentSnippetTableRules() : super(commentSnippets);

  @override
  Future<bool> canView(Jwt? jwt) async => jwt != null;

  @override
  Future<bool> canList(Jwt? jwt) async => jwt != null;

  @override
  Future<bool> canCreate(Jwt? jwt) async => jwt != null;

  @override
  Future<bool> canUpdate(Jwt? jwt) async => jwt != null;

  @override
  Future<bool> canDelete(Jwt? jwt) async => false;
}
