// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/schemas/comment_snippets.dart';
import 'package:zonai_schema/zonai_schema.dart';

CommentSnippetRowRules main() => CommentSnippetRowRules();

/// A teacher sees and changes only their own rows. Ownership is checked on
/// both sides of an update so a row can't be handed to someone else; hard
/// deletes are refused (sync deletes are tombstones).
final class CommentSnippetRowRules
    extends RowRules<CommentSnippetTable, CommentSnippet> {
  CommentSnippetRowRules() : super(commentSnippets);

  bool _owns(Jwt? jwt, CommentSnippet row) =>
      jwt != null && jwt.userId.value == row.ownerId;

  @override
  Future<bool> canView(Jwt? jwt, CommentSnippet row) async => _owns(jwt, row);

  @override
  Future<bool> canCreate(Jwt? jwt, CommentSnippet row) async => _owns(jwt, row);

  @override
  Future<bool> canUpdate(
    Jwt? jwt,
    CommentSnippet before,
    CommentSnippet after,
  ) async => _owns(jwt, before) && _owns(jwt, after);

  @override
  Future<bool> canDelete(Jwt? jwt, CommentSnippet row) async => false;
}
