// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/schemas/courses.dart';
import 'package:zonai_schema/zonai_schema.dart';

CourseTableRules main() => CourseTableRules();

/// Signed-in users may ask; the row rules decide. canUpdate must be allowed
/// here: zonai checks table rules BEFORE looking the row up.
final class CourseTableRules extends TableRules<CourseTable, Course> {
  CourseTableRules() : super(courses);

  @override
  Future<bool> canView(Jwt? jwt) async => jwt != null;

  @override
  Future<bool> canList(Jwt? jwt) async => jwt != null;

  @override
  Future<bool> canCreate(Jwt? jwt) async => jwt != null;

  @override
  Future<bool> canUpdate(Jwt? jwt) async => jwt != null;

  /// Deleting is allowed here so a teacher can delete their account (App
  /// Store guideline 5.1.1(v)); the row rules limit it to their own rows.
  /// Everyday sync deletes are still tombstones (an update), never these.
  @override
  Future<bool> canDelete(Jwt? jwt) async => jwt != null;
}
