// GENERATED by tool/gen/server_schema.py -- edit the spec there, not this file.
import 'package:rubric_server/src/schemas/rubrics.dart';
import 'package:zonai_schema/zonai_schema.dart';

RubricRowRules main() => RubricRowRules();

/// A teacher sees and changes only their own rows. Ownership is checked on
/// both sides of an update so a row can't be handed to someone else; hard
/// deletes are refused (sync deletes are tombstones).
final class RubricRowRules extends RowRules<RubricTable, Rubric> {
  RubricRowRules() : super(rubrics);

  bool _owns(Jwt? jwt, Rubric row) =>
      jwt != null && jwt.userId.value == row.ownerId;

  /// Reads are narrowed to the caller's rows (zonai #45): an unscoped list
  /// returns "your rows" instead of a 403, and counts take the plain-COUNT
  /// path while still counting only what the caller may see. canView still
  /// runs on every row in scope.
  @override
  Future<Where?> viewScope(Jwt? jwt) async =>
      jwt == null ? null : Eq('owner_id', jwt.userId.value);

  @override
  Future<bool> canView(Jwt? jwt, Rubric row) async => _owns(jwt, row);

  @override
  Future<bool> canCreate(Jwt? jwt, Rubric row) async => _owns(jwt, row);

  @override
  Future<bool> canUpdate(Jwt? jwt, Rubric before, Rubric after) async =>
      _owns(jwt, before) && _owns(jwt, after);

  @override
  Future<bool> canDelete(Jwt? jwt, Rubric row) async => false;
}
